# -*- coding: utf-8 -*-
"""irisGraphviz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o2SFIRrdXqkGp5IWgkdcmg1OaMcY7Nsg
"""

from sklearn.tree import export_graphviz
export_graphviz(
    tree_model,
    out_file = "iris_tree.dot",
    feature_names = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'],
    class_names = ['Iris-setosa', 'Iris-versicolor', 'Iris-virgincia'],
    rounded = True,
    filled = True
)