# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o2SFIRrdXqkGp5IWgkdcmg1OaMcY7Nsg
"""

from sklearn.tree import DecisionTreeClassifier
import pandas as pd
from sklearn.datasets import load_iris
iris = pd.read_csv('Iris.csv')
iris.head()
iris.drop('Id', axis=1,inplace=True)

x = iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = iris['Species']

# membuat model decision tree
tree_model = DecisionTreeClassifier()
# melakukan pelatihan terhadap data
tree_model.fit(x,y)

# tahap prediksi
tree_model.predict([[6.2, 3.4, 5.4, 2.3]])