# -*- coding: utf-8 -*-
"""latihanSVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mYIPbVBE1Hp7FB1hO60vqDi0vH8AXlfh
"""

import pandas as pd
df = pd.read_csv('diabetes.csv')

# memisahkan data atribut pada dataset dan menyimpannya pad sebuah variabel 
X = df[df.columns[:8]]

# memisahkan label pada dataset dan menyimpannya pada sebuah variabel
y = df['Outcome']

from sklearn.preprocessing import StandardScaler

# standarisasi nilai pada datset
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

from sklearn.svm import SVC

clf = SVC()
clf.fit(X_train, y_train)
clf.score(X_test, y_test)