# -*- coding: utf-8 -*-
"""latihanSVR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15upxQpUoRWqvKh8l12XxQTgKXBFI-E9i
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

data = pd.read_csv('Salary_Data.csv')

import numpy as np
X = data['YearsExperience']
y = data['Salary']
X = X[:,np.newaxis]

# membuat model SVR
from sklearn.svm import SVR
model = SVR(C=1000, gamma=0.05, kernel='rbf')
model.fit(X,y)

# visualisasi data
import matplotlib.pyplot as plt
plt.scatter(X,y)
plt.plot(X, model.predict(X))