# -*- coding: utf-8 -*-
"""linearRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19KK6jDYXFhM6Jc3G5VtSvWcy3BW0mpb8
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np 
import matplotlib.pyplot as plt
# buat data jumlah kamar
bedrooms = np.array([1,1,2,2,3,4,4,5,5,5])
# data harga rumah dalam Dollar
house_price = np.array([15000, 18000, 27000, 34000, 50000, 68000, 65000, 81000,85000, 90000])
# menampilkan scartter plot dari dataset
# %matplotlib inline


from sklearn.linear_model import LinearRegression
bedrooms = bedrooms.reshape(-1,1)
linreg = LinearRegression()
linreg.fit(bedrooms,house_price)

plt.scatter(bedrooms, house_price)
plt.plot(bedrooms, linreg.predict(bedrooms))